export type WizardStep =
  | 'couple-details'
  | 'family-details'
  | 'events'
  | 'design-customize'
  | 'music'
  | 'photos'
  | 'rsvp'
  | 'live-preview'
  | 'export-share';

export type CustomizableField =
  | 'accent-color'
  | 'music-mood'
  | 'language'
  | 'hashtag'
  | 'dress-code'
  | 'gift-registry'
  | 'live-stream'
  | 'couple-photos'
  | 'family-photos'
  | 'love-story'
  | 'family-message'
  | 'blessing-quote'
  | 'whatsapp-rsvp';

export interface TemplateWizardConfig {
  steps: WizardStep[];
  customizableFields: CustomizableField[];
  requiresPhotos: boolean;
  requiresFamily: boolean;
  requiresLoveStory: boolean;
  maxEvents: number;
  notes?: string;
}

export interface WeddingTemplate {
  id: string;
  name: string;
  tagline: string;
  ceremony: 'wedding' | 'engagement' | 'mehndi' | 'sangeet' | 'haldi' | 'reception';
  style: 'traditional' | 'luxury' | 'minimal' | 'bollywood' | 'destination' | 'festive';
  region: 'north-indian' | 'south-indian' | 'punjabi' | 'bengali' | 'rajasthani' | 'kerala' | 'pan-indian' | 'modern' | 'destination';
  mood: 'romantic' | 'festive' | 'royal' | 'modern' | 'rustic' | 'playful';
  budgetTier: 'free' | 'premium';
  designTheme: string;
  cardGradient: string;
  cardBorder: string;
  accentColor: string;
  swatches: string[];
  music: string;
  tags: string[];
  collection?: string;
  isPremium: boolean;
  isNew: boolean;
  isTrending: boolean;
  usedByCount: number;
  heroEmoji: string;
  previewBgClass: string;
  previewAnimation: 'stars' | 'petals' | 'bloom' | 'particles' | 'sparkle' | 'wave' | 'garba' | 'rain' | 'mandala' | 'shimmer' | 'glow';
  wizard: TemplateWizardConfig;
}

const DEFAULT_FULL_WIZARD: TemplateWizardConfig = {
  steps: ['couple-details', 'family-details', 'events', 'design-customize', 'music', 'photos', 'rsvp', 'live-preview', 'export-share'],
  customizableFields: ['accent-color', 'music-mood', 'language', 'hashtag', 'couple-photos', 'family-photos', 'love-story', 'family-message', 'blessing-quote', 'whatsapp-rsvp', 'gift-registry', 'live-stream', 'dress-code'],
  requiresPhotos: true,
  requiresFamily: true,
  requiresLoveStory: true,
  maxEvents: 6,
};

const SHORT_WIZARD: TemplateWizardConfig = {
  steps: ['couple-details', 'events', 'design-customize', 'rsvp', 'export-share'],
  customizableFields: ['accent-color', 'music-mood', 'language', 'whatsapp-rsvp'],
  requiresPhotos: false,
  requiresFamily: false,
  requiresLoveStory: false,
  maxEvents: 2,
};

const MEDIUM_WIZARD: TemplateWizardConfig = {
  steps: ['couple-details', 'family-details', 'events', 'design-customize', 'photos', 'rsvp', 'export-share'],
  customizableFields: ['accent-color', 'music-mood', 'language', 'hashtag', 'couple-photos', 'family-message', 'blessing-quote', 'whatsapp-rsvp', 'gift-registry'],
  requiresPhotos: true,
  requiresFamily: true,
  requiresLoveStory: false,
  maxEvents: 4,
};

export const TEMPLATES: WeddingTemplate[] = [
  // === VELORIA SIGNATURES ===
  {
    id: 'royal-noor',
    name: 'The Royal Noor',
    tagline: 'A cinematic tribute to a love that shines like gold.',
    ceremony: 'wedding',
    style: 'luxury',
    region: 'north-indian',
    mood: 'royal',
    budgetTier: 'premium',
    designTheme: 'royal-noor',
    cardGradient: 'from-[#0F0F0F] via-[#1C1400] to-[#0F0F0F]',
    cardBorder: 'border-[#D4AF37]/50',
    accentColor: '#D4AF37',
    swatches: ['#D4AF37', '#5E0B15', '#0F0F0F', '#F5F5F5'],
    music: 'sufi',
    tags: ['Featured', 'Veloria Signature', 'Cinematic', 'Royal'],
    collection: 'veloria-signature',
    isPremium: true,
    isNew: true,
    isTrending: true,
    usedByCount: 0,
    heroEmoji: '🏛️',
    previewBgClass: 'bg-gradient-to-br from-[#0F0F0F] via-[#1C1400] to-[#0F0F0F]',
    previewAnimation: 'stars',
    wizard: DEFAULT_FULL_WIZARD,
  },
  {
    id: 'maharaja-gold',
    name: 'Maharaja Gold',
    tagline: 'Regal grandeur meets timeless tradition',
    ceremony: 'wedding',
    style: 'luxury',
    region: 'north-indian',
    mood: 'royal',
    budgetTier: 'free',
    designTheme: 'royal-maharaja',
    cardGradient: 'from-[#1A1200] via-[#3D2B00] to-[#1A1200]',
    cardBorder: 'border-[#D4AF37]/50',
    accentColor: '#D4AF37',
    swatches: ['#D4AF37', '#8B732A', '#1A1200', '#F7E7CE'],
    music: 'romantic',
    tags: ['Most Popular', 'Royal', 'Gold'],
    collection: 'big-fat-indian',
    isPremium: false,
    isNew: false,
    isTrending: true,
    usedByCount: 4821,
    heroEmoji: '👑',
    previewBgClass: 'bg-gradient-to-br from-[#1A1200] via-[#3D2B00] to-[#1A1200]',
    previewAnimation: 'sparkle',
    wizard: DEFAULT_FULL_WIZARD,
  },
  {
    id: 'marigold-royale',
    name: 'Marigold Royale',
    tagline: 'Crimson velvet & Mughal gold — Bollywood royal grandeur',
    ceremony: 'wedding',
    style: 'bollywood',
    region: 'pan-indian',
    mood: 'royal',
    budgetTier: 'premium',
    designTheme: 'marigold-royale',
    cardGradient: 'from-[#3D0A14] via-[#1C0509] to-[#0A0003]',
    cardBorder: 'border-[#C9973A]/50',
    accentColor: '#C9973A',
    swatches: ['#C9973A', '#3D0A14', '#E8841A', '#FAF5EC'],
    music: 'bollywood',
    tags: ['Marigold', 'Crimson', 'Mughal', 'Cinematic'],
    collection: 'big-fat-indian',
    isPremium: true,
    isNew: true,
    isTrending: true,
    usedByCount: 312,
    heroEmoji: '🌼',
    previewBgClass: 'bg-gradient-to-br from-[#3D0A14] via-[#1C0509] to-[#0A0003]',
    previewAnimation: 'petals',
    wizard: DEFAULT_FULL_WIZARD,
  },
  {
    id: 'midnight-sahara',
    name: 'Midnight Sahara',
    tagline: 'Desert sands, star-lit skies & Rajasthani splendour',
    ceremony: 'wedding',
    style: 'luxury',
    region: 'rajasthani',
    mood: 'royal',
    budgetTier: 'premium',
    designTheme: 'midnight-sahara',
    cardGradient: 'from-[#0A0512] via-[#1A0B2E] to-[#0A0512]',
    cardBorder: 'border-[#9B59B6]/40',
    accentColor: '#C4A35A',
    swatches: ['#C4A35A', '#9B59B6', '#0A0512', '#F5E6C8'],
    music: 'folk',
    tags: ['Rajasthani', 'Desert', 'Star-lit', 'Heritage'],
    collection: 'heritage-hues',
    isPremium: true,
    isNew: true,
    isTrending: true,
    usedByCount: 189,
    heroEmoji: '🌙',
    previewBgClass: 'bg-gradient-to-br from-[#0A0512] via-[#1A0B2E] to-[#0A0512]',
    previewAnimation: 'stars',
    wizard: DEFAULT_FULL_WIZARD,
  },
  {
    id: 'ivory-blossom',
    name: 'Ivory Blossom',
    tagline: 'Soft whites, blush petals & timeless bridal grace',
    ceremony: 'wedding',
    style: 'minimal',
    region: 'pan-indian',
    mood: 'romantic',
    budgetTier: 'free',
    designTheme: 'ivory-blossom',
    cardGradient: 'from-[#1A0A14] via-[#2D1A24] to-[#1A0A14]',
    cardBorder: 'border-[#F5D0D8]/40',
    accentColor: '#F5D0D8',
    swatches: ['#F5D0D8', '#D4B5C5', '#1A0A14', '#FAF5F7'],
    music: 'romantic',
    tags: ['Minimal', 'Blush', 'Bridal', 'Elegant'],
    collection: 'minimal-soulful',
    isPremium: false,
    isNew: true,
    isTrending: false,
    usedByCount: 156,
    heroEmoji: '🌸',
    previewBgClass: 'bg-gradient-to-br from-[#1A0A14] via-[#2D1A24] to-[#1A0A14]',
    previewAnimation: 'bloom',
    wizard: DEFAULT_FULL_WIZARD,
  },
  {
    id: 'rose-anand',
    name: 'Rosé Anand',
    tagline: 'Dusty rose silk & champagne for the modern Punjabi bride',
    ceremony: 'wedding',
    style: 'luxury',
    region: 'punjabi',
    mood: 'romantic',
    budgetTier: 'premium',
    designTheme: 'rose-anand',
    cardGradient: 'from-[#2A0A18] via-[#4A1530] to-[#2A0A18]',
    cardBorder: 'border-[#E8A0B0]/40',
    accentColor: '#E8A0B0',
    swatches: ['#E8A0B0', '#C9973A', '#2A0A18', '#FFF0F3'],
    music: 'romantic',
    tags: ['Rosé', 'Punjabi', 'Modern', 'Champagne', 'Luxury'],
    collection: 'pastel-poetry',
    isPremium: true,
    isNew: true,
    isTrending: false,
    usedByCount: 98,
    heroEmoji: '🌹',
    previewBgClass: 'bg-gradient-to-br from-[#2A0A18] via-[#4A1530] to-[#2A0A18]',
    previewAnimation: 'particles',
    wizard: DEFAULT_FULL_WIZARD,
  },
  {
    id: 'sindoor-velvet',
    name: 'Sindoor Velvet',
    tagline: 'Velvet crimson & Banarasi gold — deep Indian bridal opulence',
    ceremony: 'wedding',
    style: 'traditional',
    region: 'north-indian',
    mood: 'royal',
    budgetTier: 'premium',
    designTheme: 'sindoor-velvet',
    cardGradient: 'from-[#1A0000] via-[#4A0005] to-[#1A0000]',
    cardBorder: 'border-[#DC143C]/40',
    accentColor: '#DC143C',
    swatches: ['#DC143C', '#C9973A', '#1A0000', '#FAF5EC'],
    music: 'classical',
    tags: ['Sindoor', 'Banarasi', 'Crimson', 'Velvet', 'Traditional'],
    collection: 'heritage-hues',
    isPremium: true,
    isNew: true,
    isTrending: false,
    usedByCount: 134,
    heroEmoji: '🔴',
    previewBgClass: 'bg-gradient-to-br from-[#1A0000] via-[#4A0005] to-[#1A0000]',
    previewAnimation: 'particles',
    wizard: DEFAULT_FULL_WIZARD,
  },
  // === NEW TEMPLATES ===
  {
    id: 'gujarati-garba',
    name: 'Gujarati Garba',
    tagline: 'Mirror-work magic, circular garba energy, saffron & joy',
    ceremony: 'wedding',
    style: 'festive',
    region: 'pan-indian',
    mood: 'festive',
    budgetTier: 'free',
    designTheme: 'gujarati-garba',
    cardGradient: 'from-[#3D1500] via-[#1A0800] to-[#0A0300]',
    cardBorder: 'border-[#FF6B35]/50',
    accentColor: '#FF6B35',
    swatches: ['#FF6B35', '#FFD700', '#D62598', '#FF9500'],
    music: 'folk',
    tags: ['Gujarati', 'Garba', 'Festive', 'Mirror Work', 'New'],
    collection: 'regional-gems',
    isPremium: false,
    isNew: true,
    isTrending: true,
    usedByCount: 0,
    heroEmoji: '🪩',
    previewBgClass: 'bg-gradient-to-br from-[#3D1500] via-[#1A0800] to-[#0A0300]',
    previewAnimation: 'garba',
    wizard: DEFAULT_FULL_WIZARD,
  },
  {
    id: 'kerala-monsoon',
    name: 'Kerala Monsoon',
    tagline: 'Temple gold & rain-drop serenity — deep south heritage',
    ceremony: 'wedding',
    style: 'traditional',
    region: 'kerala',
    mood: 'romantic',
    budgetTier: 'free',
    designTheme: 'kerala-monsoon',
    cardGradient: 'from-[#0D2B1A] via-[#061510] to-[#020A06]',
    cardBorder: 'border-[#D4A843]/40',
    accentColor: '#D4A843',
    swatches: ['#D4A843', '#4A8B6F', '#0D4A2A', '#F5F0E8'],
    music: 'classical',
    tags: ['Kerala', 'South Indian', 'Temple', 'Heritage', 'New'],
    collection: 'heritage-hues',
    isPremium: false,
    isNew: true,
    isTrending: false,
    usedByCount: 0,
    heroEmoji: '🌿',
    previewBgClass: 'bg-gradient-to-br from-[#0D2B1A] via-[#061510] to-[#020A06]',
    previewAnimation: 'rain',
    wizard: DEFAULT_FULL_WIZARD,
  },
  {
    id: 'marathi-peshwa',
    name: 'Marathi Peshwa',
    tagline: 'Paithani silk, deep purple heritage & Pune royalty',
    ceremony: 'wedding',
    style: 'traditional',
    region: 'pan-indian',
    mood: 'royal',
    budgetTier: 'free',
    designTheme: 'marathi-peshwa',
    cardGradient: 'from-[#2D0F45] via-[#1A0326] to-[#0A0115]',
    cardBorder: 'border-[#C9973A]/40',
    accentColor: '#C9973A',
    swatches: ['#C9973A', '#4A0E6B', '#D4A8FF', '#FAF5EC'],
    music: 'classical',
    tags: ['Marathi', 'Peshwa', 'Paithani', 'Heritage', 'New'],
    collection: 'regional-gems',
    isPremium: false,
    isNew: true,
    isTrending: false,
    usedByCount: 0,
    heroEmoji: '🪷',
    previewBgClass: 'bg-gradient-to-br from-[#2D0F45] via-[#1A0326] to-[#0A0115]',
    previewAnimation: 'mandala',
    wizard: DEFAULT_FULL_WIZARD,
  },
  {
    id: 'nri-london',
    name: 'NRI London',
    tagline: 'Contemporary minimal elegance for the global Indian couple',
    ceremony: 'wedding',
    style: 'luxury',
    region: 'destination',
    mood: 'modern',
    budgetTier: 'premium',
    designTheme: 'nri-london',
    cardGradient: 'from-[#111114] via-[#0A0A0C] to-[#050508]',
    cardBorder: 'border-[#C9A84C]/30',
    accentColor: '#C9A84C',
    swatches: ['#C9A84C', '#A8A8B3', '#1C1C1E', '#F8F5F0'],
    music: 'ambient',
    tags: ['NRI', 'London', 'Dubai', 'Contemporary', 'Global', 'New'],
    collection: 'destination-dreams',
    isPremium: true,
    isNew: true,
    isTrending: true,
    usedByCount: 0,
    heroEmoji: '✨',
    previewBgClass: 'bg-gradient-to-br from-[#111114] via-[#0A0A0C] to-[#050508]',
    previewAnimation: 'shimmer',
    wizard: DEFAULT_FULL_WIZARD,
  },
  {
    id: 'goa-beach',
    name: 'Goa Beach',
    tagline: 'Sunset coral, ocean waves & tropical destination bliss',
    ceremony: 'wedding',
    style: 'destination',
    region: 'destination',
    mood: 'rustic',
    budgetTier: 'free',
    designTheme: 'goa-beach',
    cardGradient: 'from-[#1E3A4A] via-[#1A2E38] to-[#0D1F28]',
    cardBorder: 'border-[#E8634A]/40',
    accentColor: '#E8634A',
    swatches: ['#E8634A', '#1E6B8C', '#2EC4B6', '#F5E6C8'],
    music: 'ambient',
    tags: ['Goa', 'Beach', 'Destination', 'Sunset', 'Tropical', 'New'],
    collection: 'destination-dreams',
    isPremium: false,
    isNew: true,
    isTrending: false,
    usedByCount: 0,
    heroEmoji: '🌊',
    previewBgClass: 'bg-gradient-to-br from-[#1E3A4A] via-[#1A2E38] to-[#0D1F28]',
    previewAnimation: 'wave',
    wizard: DEFAULT_FULL_WIZARD,
  },
  // === EXISTING TEMPLATES (rest of library) ===
  {
    id: 'crimson-shaadi',
    name: 'Crimson Shaadi',
    tagline: 'Classic deep red Bollywood grandeur',
    ceremony: 'wedding',
    style: 'bollywood',
    region: 'north-indian',
    mood: 'festive',
    budgetTier: 'free',
    designTheme: 'bollywood',
    cardGradient: 'from-[#1A0000] via-[#4A0000] to-[#1A0000]',
    cardBorder: 'border-[#DC143C]/50',
    accentColor: '#DC143C',
    swatches: ['#DC143C', '#D4AF37', '#8B0000', '#FFFFFF'],
    music: 'bollywood',
    tags: ['Wedding', 'Red', 'Bollywood', 'Popular'],
    collection: 'big-fat-indian',
    isPremium: false,
    isNew: false,
    isTrending: true,
    usedByCount: 3567,
    heroEmoji: '❤️',
    previewBgClass: 'bg-gradient-to-br from-[#1A0000] via-[#4A0000] to-[#1A0000]',
    previewAnimation: 'particles',
    wizard: DEFAULT_FULL_WIZARD,
  },
  {
    id: 'bougainvillea-garden',
    name: 'Bougainvillea Garden',
    tagline: 'Lush florals, soft romance, destination dreams',
    ceremony: 'wedding',
    style: 'destination',
    region: 'destination',
    mood: 'romantic',
    budgetTier: 'free',
    designTheme: 'floral',
    cardGradient: 'from-[#3D0A2E] via-[#7B2D5E] to-[#3D0A2E]',
    cardBorder: 'border-[#FFC0CB]/40',
    accentColor: '#FF6B9D',
    swatches: ['#FF6B9D', '#FFC0CB', '#7B2D5E', '#FFFFFF'],
    music: 'romantic',
    tags: ['Floral', 'Destination', 'Garden'],
    collection: 'destination-dreams',
    isPremium: false,
    isNew: true,
    isTrending: true,
    usedByCount: 1203,
    heroEmoji: '🌸',
    previewBgClass: 'bg-gradient-to-br from-[#3D0A2E] via-[#7B2D5E] to-[#3D0A2E]',
    previewAnimation: 'petals',
    wizard: MEDIUM_WIZARD,
  },
  {
    id: 'midnight-silk',
    name: 'Midnight Silk',
    tagline: 'Dark luxury for unforgettable receptions',
    ceremony: 'reception',
    style: 'luxury',
    region: 'modern',
    mood: 'modern',
    budgetTier: 'premium',
    designTheme: 'dark-luxury',
    cardGradient: 'from-[#0A0A0F] via-[#1A1A2E] to-[#0A0A0F]',
    cardBorder: 'border-white/10',
    accentColor: '#C0C0C0',
    swatches: ['#C0C0C0', '#1A1A2E', '#0A0A0F', '#E8E8E8'],
    music: 'orchestra',
    tags: ['Premium', 'Dark', 'Luxury', 'Reception'],
    collection: 'minimal-soulful',
    isPremium: true,
    isNew: false,
    isTrending: true,
    usedByCount: 2341,
    heroEmoji: '🌙',
    previewBgClass: 'bg-gradient-to-br from-[#0A0A0F] via-[#1A1A2E] to-[#0A0A0F]',
    previewAnimation: 'shimmer',
    wizard: MEDIUM_WIZARD,
  },
  {
    id: 'sindoor-dreams',
    name: 'Sindoor Dreams',
    tagline: 'Red & white Bengali elegance',
    ceremony: 'wedding',
    style: 'traditional',
    region: 'bengali',
    mood: 'romantic',
    budgetTier: 'free',
    designTheme: 'bengali',
    cardGradient: 'from-[#3D0000] via-[#8B0000] to-[#3D0000]',
    cardBorder: 'border-white/30',
    accentColor: '#FFFFFF',
    swatches: ['#CC0000', '#FFFFFF', '#8B0000', '#FF6666'],
    music: 'traditional',
    tags: ['Bengali', 'Traditional', 'Red & White'],
    collection: 'heritage-hues',
    isPremium: false,
    isNew: false,
    isTrending: false,
    usedByCount: 987,
    heroEmoji: '🪷',
    previewBgClass: 'bg-gradient-to-br from-[#3D0000] via-[#8B0000] to-[#3D0000]',
    previewAnimation: 'particles',
    wizard: DEFAULT_FULL_WIZARD,
  },
  {
    id: 'pastel-bloom',
    name: 'Pastel Bloom',
    tagline: 'Soft pastels, modern romance, clean elegance',
    ceremony: 'engagement',
    style: 'minimal',
    region: 'pan-indian',
    mood: 'romantic',
    budgetTier: 'free',
    designTheme: 'spring-blossom',
    cardGradient: 'from-[#2D1B35] via-[#4A2B50] to-[#2D1B35]',
    cardBorder: 'border-[#CE93D8]/40',
    accentColor: '#CE93D8',
    swatches: ['#F48FB1', '#CE93D8', '#FFFFFF', '#F8BBD0'],
    music: 'romantic',
    tags: ['Engagement', 'Pastel', 'Minimal'],
    collection: 'pastel-poetry',
    isPremium: false,
    isNew: true,
    isTrending: false,
    usedByCount: 654,
    heroEmoji: '💜',
    previewBgClass: 'bg-gradient-to-br from-[#2D1B35] via-[#4A2B50] to-[#2D1B35]',
    previewAnimation: 'bloom',
    wizard: SHORT_WIZARD,
  },
  {
    id: 'sangeet-nights',
    name: 'Sangeet Nights',
    tagline: 'Bollywood lights, dance, and drama',
    ceremony: 'sangeet',
    style: 'bollywood',
    region: 'north-indian',
    mood: 'festive',
    budgetTier: 'free',
    designTheme: 'bollywood',
    cardGradient: 'from-[#2A0010] via-[#6B0030] to-[#2A0010]',
    cardBorder: 'border-[#FF1493]/40',
    accentColor: '#FF1493',
    swatches: ['#FF1493', '#FFD700', '#6B0030', '#FF69B4'],
    music: 'bollywood',
    tags: ['Sangeet', 'Bollywood', 'Trending'],
    collection: 'big-fat-indian',
    isPremium: false,
    isNew: false,
    isTrending: true,
    usedByCount: 3102,
    heroEmoji: '💃',
    previewBgClass: 'bg-gradient-to-br from-[#2A0010] via-[#6B0030] to-[#2A0010]',
    previewAnimation: 'sparkle',
    wizard: SHORT_WIZARD,
  },
  {
    id: 'mehndi-magic',
    name: 'Mehndi Magic',
    tagline: 'Earthy hues and intricate patterns',
    ceremony: 'mehndi',
    style: 'festive',
    region: 'rajasthani',
    mood: 'festive',
    budgetTier: 'free',
    designTheme: 'rajasthani',
    cardGradient: 'from-[#1A0A00] via-[#4A2500] to-[#1A0A00]',
    cardBorder: 'border-[#D4AF37]/40',
    accentColor: '#8B6914',
    swatches: ['#8B6914', '#D4AF37', '#4A2500', '#F4A460'],
    music: 'folk',
    tags: ['Mehndi', 'Rajasthani', 'Earthy'],
    collection: 'regional-gems',
    isPremium: false,
    isNew: false,
    isTrending: false,
    usedByCount: 1456,
    heroEmoji: '🌿',
    previewBgClass: 'bg-gradient-to-br from-[#1A0A00] via-[#4A2500] to-[#1A0A00]',
    previewAnimation: 'glow',
    wizard: SHORT_WIZARD,
  },
  {
    id: 'kerala-mural',
    name: 'Kerala Mural',
    tagline: 'Temple art, coconut groves, pure tradition',
    ceremony: 'wedding',
    style: 'traditional',
    region: 'kerala',
    mood: 'royal',
    budgetTier: 'free',
    designTheme: 'south-indian',
    cardGradient: 'from-[#001A00] via-[#003300] to-[#001A00]',
    cardBorder: 'border-[#FFD700]/50',
    accentColor: '#FFD700',
    swatches: ['#FFD700', '#006600', '#FFFFFF', '#FF6600'],
    music: 'classical',
    tags: ['Kerala', 'South Indian', 'Temple'],
    collection: 'heritage-hues',
    isPremium: false,
    isNew: false,
    isTrending: false,
    usedByCount: 743,
    heroEmoji: '🪔',
    previewBgClass: 'bg-gradient-to-br from-[#001A00] via-[#003300] to-[#001A00]',
    previewAnimation: 'glow',
    wizard: DEFAULT_FULL_WIZARD,
  },
  {
    id: 'champagne-toast',
    name: 'Champagne Toast',
    tagline: 'Modern luxury for elite receptions',
    ceremony: 'reception',
    style: 'luxury',
    region: 'destination',
    mood: 'modern',
    budgetTier: 'premium',
    designTheme: 'premium-minimal',
    cardGradient: 'from-[#1A1400] via-[#2E2400] to-[#1A1400]',
    cardBorder: 'border-[#F5CBA7]/30',
    accentColor: '#F5CBA7',
    swatches: ['#F5CBA7', '#C9B062', '#1A1400', '#FFFFFF'],
    music: 'jazz',
    tags: ['Reception', 'Premium', 'Champagne'],
    collection: 'destination-dreams',
    isPremium: true,
    isNew: false,
    isTrending: false,
    usedByCount: 892,
    heroEmoji: '🥂',
    previewBgClass: 'bg-gradient-to-br from-[#1A1400] via-[#2E2400] to-[#1A1400]',
    previewAnimation: 'sparkle',
    wizard: MEDIUM_WIZARD,
  },
  {
    id: 'haldi-sunshine',
    name: 'Haldi Sunshine',
    tagline: 'Bright, playful, and joyous yellow vibes',
    ceremony: 'haldi',
    style: 'festive',
    region: 'pan-indian',
    mood: 'playful',
    budgetTier: 'free',
    designTheme: 'traditional',
    cardGradient: 'from-[#1A1000] via-[#3D2800] to-[#1A1000]',
    cardBorder: 'border-[#FFD700]/60',
    accentColor: '#FFD700',
    swatches: ['#FFD700', '#FF8C00', '#FFF176', '#FF6B00'],
    music: 'folk',
    tags: ['Haldi', 'Yellow', 'Playful', 'Festive'],
    collection: 'regional-gems',
    isPremium: false,
    isNew: false,
    isTrending: false,
    usedByCount: 1834,
    heroEmoji: '☀️',
    previewBgClass: 'bg-gradient-to-br from-[#1A1000] via-[#3D2800] to-[#1A1000]',
    previewAnimation: 'glow',
    wizard: SHORT_WIZARD,
  },
  {
    id: 'royal-amethyst',
    name: 'Royal Amethyst',
    tagline: 'Deep purple royalty and golden grandeur',
    ceremony: 'wedding',
    style: 'luxury',
    region: 'north-indian',
    mood: 'royal',
    budgetTier: 'premium',
    designTheme: 'fantasy-royal',
    cardGradient: 'from-[#0F0020] via-[#2D0060] to-[#0F0020]',
    cardBorder: 'border-[#9B59B6]/50',
    accentColor: '#9B59B6',
    swatches: ['#9B59B6', '#D4AF37', '#2D0060', '#E8DAFF'],
    music: 'orchestra',
    tags: ['Premium', 'Royal', 'Purple'],
    collection: 'veloria-signature',
    isPremium: true,
    isNew: true,
    isTrending: true,
    usedByCount: 567,
    heroEmoji: '💜',
    previewBgClass: 'bg-gradient-to-br from-[#0F0020] via-[#2D0060] to-[#0F0020]',
    previewAnimation: 'stars',
    wizard: DEFAULT_FULL_WIZARD,
  },
  {
    id: 'ivory-minimal',
    name: 'Ivory Minimal',
    tagline: 'Clean, modern, effortlessly chic',
    ceremony: 'wedding',
    style: 'minimal',
    region: 'modern',
    mood: 'modern',
    budgetTier: 'free',
    designTheme: 'premium-minimal',
    cardGradient: 'from-[#0A0A0A] via-[#1A1A1A] to-[#0A0A0A]',
    cardBorder: 'border-white/15',
    accentColor: '#F5F5F0',
    swatches: ['#F5F5F0', '#D4D4D0', '#1A1A1A', '#888888'],
    music: 'ambient',
    tags: ['Minimal', 'Clean', 'Modern'],
    collection: 'minimal-soulful',
    isPremium: false,
    isNew: false,
    isTrending: false,
    usedByCount: 2109,
    heroEmoji: '🤍',
    previewBgClass: 'bg-gradient-to-br from-[#0A0A0A] via-[#1A1A1A] to-[#0A0A0A]',
    previewAnimation: 'shimmer',
    wizard: MEDIUM_WIZARD,
  },
  {
    id: 'tamil-kolam',
    name: 'Tamil Kolam',
    tagline: 'Geometric kolam patterns, vibrant Dravidian spirit',
    ceremony: 'wedding',
    style: 'traditional',
    region: 'south-indian',
    mood: 'festive',
    budgetTier: 'free',
    designTheme: 'south-indian',
    cardGradient: 'from-[#1A0A00] via-[#3D1F00] to-[#1A0A00]',
    cardBorder: 'border-[#FF8C00]/50',
    accentColor: '#FF8C00',
    swatches: ['#FF8C00', '#FFD700', '#8B0000', '#FFFFFF'],
    music: 'classical',
    tags: ['Tamil', 'South Indian', 'Kolam'],
    collection: 'heritage-hues',
    isPremium: false,
    isNew: false,
    isTrending: false,
    usedByCount: 612,
    heroEmoji: '🪷',
    previewBgClass: 'bg-gradient-to-br from-[#1A0A00] via-[#3D1F00] to-[#1A0A00]',
    previewAnimation: 'glow',
    wizard: DEFAULT_FULL_WIZARD,
  },
  {
    id: 'punjabi-phulkari',
    name: 'Punjabi Phulkari',
    tagline: 'Bold colours, bhangra energy, pure joy',
    ceremony: 'wedding',
    style: 'festive',
    region: 'punjabi',
    mood: 'festive',
    budgetTier: 'free',
    designTheme: 'punjabi',
    cardGradient: 'from-[#1A0500] via-[#4A1500] to-[#1A0500]',
    cardBorder: 'border-[#FF6600]/50',
    accentColor: '#FF6600',
    swatches: ['#FF6600', '#FFD700', '#8B0000', '#00CC44'],
    music: 'folk',
    tags: ['Punjabi', 'Festive', 'Phulkari'],
    collection: 'regional-gems',
    isPremium: false,
    isNew: false,
    isTrending: false,
    usedByCount: 1267,
    heroEmoji: '🎊',
    previewBgClass: 'bg-gradient-to-br from-[#1A0500] via-[#4A1500] to-[#1A0500]',
    previewAnimation: 'garba',
    wizard: MEDIUM_WIZARD,
  },
  {
    id: 'garden-party',
    name: 'Garden Party',
    tagline: 'Open air, flowers everywhere, afternoon bliss',
    ceremony: 'engagement',
    style: 'destination',
    region: 'destination',
    mood: 'rustic',
    budgetTier: 'free',
    designTheme: 'spring-blossom',
    cardGradient: 'from-[#001A06] via-[#003010] to-[#001A06]',
    cardBorder: 'border-[#90EE90]/40',
    accentColor: '#90EE90',
    swatches: ['#90EE90', '#228B22', '#FFD700', '#FFF0F0'],
    music: 'ambient',
    tags: ['Engagement', 'Garden', 'Outdoor'],
    collection: 'destination-dreams',
    isPremium: false,
    isNew: true,
    isTrending: false,
    usedByCount: 389,
    heroEmoji: '🌻',
    previewBgClass: 'bg-gradient-to-br from-[#001A06] via-[#003010] to-[#001A06]',
    previewAnimation: 'bloom',
    wizard: SHORT_WIZARD,
  },
  {
    id: 'starry-night',
    name: 'Starry Night',
    tagline: 'Celestial romance under a thousand stars',
    ceremony: 'reception',
    style: 'luxury',
    region: 'modern',
    mood: 'romantic',
    budgetTier: 'premium',
    designTheme: 'monsoon',
    cardGradient: 'from-[#000010] via-[#000830] to-[#000010]',
    cardBorder: 'border-[#4169E1]/40',
    accentColor: '#4169E1',
    swatches: ['#4169E1', '#C0C0C0', '#000830', '#FFD700'],
    music: 'orchestra',
    tags: ['Reception', 'Stars', 'Night', 'Trending'],
    collection: 'veloria-signature',
    isPremium: true,
    isNew: false,
    isTrending: true,
    usedByCount: 1876,
    heroEmoji: '⭐',
    previewBgClass: 'bg-gradient-to-br from-[#000010] via-[#000830] to-[#000010]',
    previewAnimation: 'stars',
    wizard: MEDIUM_WIZARD,
  },
  {
    id: 'coral-sunset',
    name: 'Coral Sunset',
    tagline: 'Warm coral hues, gentle pastels, engagement bliss',
    ceremony: 'engagement',
    style: 'minimal',
    region: 'pan-indian',
    mood: 'romantic',
    budgetTier: 'free',
    designTheme: 'spring-blossom',
    cardGradient: 'from-[#1A0500] via-[#3D1500] to-[#1A0500]',
    cardBorder: 'border-[#FF7F50]/40',
    accentColor: '#FF7F50',
    swatches: ['#FF7F50', '#FFB347', '#FF6B9D', '#FFF0E6'],
    music: 'romantic',
    tags: ['Engagement', 'Coral', 'Pastel'],
    collection: 'pastel-poetry',
    isPremium: false,
    isNew: true,
    isTrending: false,
    usedByCount: 421,
    heroEmoji: '🌅',
    previewBgClass: 'bg-gradient-to-br from-[#1A0500] via-[#3D1500] to-[#1A0500]',
    previewAnimation: 'bloom',
    wizard: SHORT_WIZARD,
  },
  {
    id: 'bengal-baul',
    name: 'Bengal Baul',
    tagline: 'Mystical folk art and rich cultural soul',
    ceremony: 'wedding',
    style: 'traditional',
    region: 'bengali',
    mood: 'rustic',
    budgetTier: 'free',
    designTheme: 'bengali',
    cardGradient: 'from-[#0A0A00] via-[#2A2000] to-[#0A0A00]',
    cardBorder: 'border-[#CC8800]/50',
    accentColor: '#CC8800',
    swatches: ['#CC8800', '#8B0000', '#FFD700', '#FFFFFF'],
    music: 'folk',
    tags: ['Bengali', 'Folk', 'Cultural'],
    collection: 'heritage-hues',
    isPremium: false,
    isNew: false,
    isTrending: false,
    usedByCount: 334,
    heroEmoji: '🎭',
    previewBgClass: 'bg-gradient-to-br from-[#0A0A00] via-[#2A2000] to-[#0A0A00]',
    previewAnimation: 'glow',
    wizard: DEFAULT_FULL_WIZARD,
  },
  {
    id: 'silver-screen',
    name: 'Silver Screen',
    tagline: 'Cinematic Bollywood glamour for receptions',
    ceremony: 'reception',
    style: 'bollywood',
    region: 'modern',
    mood: 'modern',
    budgetTier: 'premium',
    designTheme: 'modern-insta',
    cardGradient: 'from-[#0A0015] via-[#1E0035] to-[#0A0015]',
    cardBorder: 'border-[#C0C0C0]/30',
    accentColor: '#C0C0C0',
    swatches: ['#C0C0C0', '#8B008B', '#FFD700', '#000015'],
    music: 'bollywood',
    tags: ['Reception', 'Cinematic', 'Trending'],
    collection: 'veloria-signature',
    isPremium: true,
    isNew: false,
    isTrending: true,
    usedByCount: 2089,
    heroEmoji: '🎬',
    previewBgClass: 'bg-gradient-to-br from-[#0A0015] via-[#1E0035] to-[#0A0015]',
    previewAnimation: 'stars',
    wizard: MEDIUM_WIZARD,
  },
];

export const CEREMONY_FILTERS = ['All', 'Wedding', 'Engagement', 'Mehndi', 'Sangeet', 'Haldi', 'Reception'];
export const STYLE_FILTERS = ['All', 'Traditional', 'Luxury', 'Minimal', 'Bollywood', 'Destination', 'Festive'];
export const REGION_FILTERS = ['All', 'North Indian', 'South Indian', 'Punjabi', 'Bengali', 'Rajasthani', 'Kerala', 'Pan Indian', 'Modern', 'Destination'];
export const MOOD_FILTERS = ['All', 'Romantic', 'Festive', 'Royal', 'Modern', 'Rustic', 'Playful'];
export const BUDGET_FILTERS = ['All', 'Free', 'Premium'];

export const CURATED_COLLECTIONS = [
  { id: 'veloria-signature', name: 'Veloria Signature', emoji: '🏛️', description: 'Our finest creations, hand-crafted by the Veloria design team', color: '#D4AF37' },
  { id: 'big-fat-indian', name: 'Big Fat Indian Wedding', emoji: '🎊', description: 'Grand celebrations for the full shaadi experience', color: '#DC143C' },
  { id: 'heritage-hues', name: 'Heritage Hues', emoji: '🏺', description: 'Traditional regional templates celebrating India\'s diverse culture', color: '#C9973A' },
  { id: 'destination-dreams', name: 'Destination Dreams', emoji: '✈️', description: 'For couples celebrating love across continents and coastlines', color: '#4169E1' },
  { id: 'pastel-poetry', name: 'Pastel Poetry', emoji: '🌸', description: 'Soft, romantic, modern — for the minimalist bride', color: '#CE93D8' },
  { id: 'minimal-soulful', name: 'Minimal & Soulful', emoji: '🤍', description: 'Less is more. Timeless and elegant for the design-conscious couple', color: '#A8A8B3' },
  { id: 'regional-gems', name: 'Regional Gems', emoji: '💎', description: 'State-specific templates that celebrate your roots', color: '#FF6B35' },
];

export const TRENDING_TEMPLATE_IDS = ['royal-noor', 'maharaja-gold', 'crimson-shaadi', 'sangeet-nights', 'marigold-royale', 'midnight-sahara', 'nri-london', 'gujarati-garba'];

export function getTemplateById(id: string): WeddingTemplate | undefined {
  return TEMPLATES.find(t => t.id === id);
}

export function filterTemplates(
  templates: WeddingTemplate[],
  {
    ceremony,
    style,
    region,
    mood,
    budget,
    search,
    collection,
  }: {
    ceremony?: string;
    style?: string;
    region?: string;
    mood?: string;
    budget?: string;
    search?: string;
    collection?: string;
  }
): WeddingTemplate[] {
  return templates.filter(t => {
    if (ceremony && ceremony !== 'All' && t.ceremony !== ceremony.toLowerCase()) return false;
    if (style && style !== 'All' && t.style !== style.toLowerCase()) return false;
    if (region && region !== 'All') {
      const regionKey = region.toLowerCase().replace(' ', '-');
      if (t.region !== regionKey) return false;
    }
    if (mood && mood !== 'All' && t.mood !== mood.toLowerCase()) return false;
    if (budget && budget !== 'All' && t.budgetTier !== budget.toLowerCase()) return false;
    if (collection && t.collection !== collection) return false;
    if (search) {
      const q = search.toLowerCase();
      if (!t.name.toLowerCase().includes(q) && !t.tagline.toLowerCase().includes(q) && !t.tags.some(tag => tag.toLowerCase().includes(q))) {
        return false;
      }
    }
    return true;
  });
}

export function getWizardStepLabel(step: WizardStep): string {
  const labels: Record<WizardStep, string> = {
    'couple-details': 'Couple Details',
    'family-details': 'Family Details',
    'events': 'Events',
    'design-customize': 'Customize',
    'music': 'Music',
    'photos': 'Photos',
    'rsvp': 'RSVP',
    'live-preview': 'Preview',
    'export-share': 'Share',
  };
  return labels[step];
}
